### ISSUE TITLE
Javascript track courses to be completed

### ISSUE THREAD

**Issue by camobrien343** [camobrien343/Treehouse#2]
## TODO

![Image of Cage](https://img.buzzfeed.com/buzzfeed-static/static/2014-01/campaign_images/webdr06/7/14/50-reasons-why-nicolas-cage-is-the-greatest-human-1-5571-1389124720-1_big.jpg)
*Courses left to do*
- [ ] Take a nap
- [ ] Take another nap
- [ ] Fit a nap in
- [ ] wake-up
- [ ] Take another nap

:tada::tada::tada::tada::tada::tada::tada::tada:
cc @camobrien343
